# Config file for https://github.com/FooSoft/homemaker

##################################################################################
# WINDOWS
##################################################################################

[tasks.totalcmd]
    cmds = [
        ["reg", "add", 'HKCU\Software\Ghisler\Total Commander', "/v", "IniFileName", "/d", '%LocalAppData%\totalcmd\wincmd.ini', "/f"],
        ["reg", "add", 'HKCU\Software\Ghisler\Total Commander', "/v", "FtpIniName",  "/d", '%LocalAppData%\totalcmd\wcx_ftp.ini', "/f"],
    ]
    links = [
        ["AppData/local/totalcmd/wincmd.ini", "totalcmd/wincmd.ini"],
        ["AppData/local/totalcmd/wincmd_usermenu.ini", "totalcmd/wincmd_usermenu.ini"],
        ["AppData/local/totalcmd/usercmd.ini", "totalcmd/usercmd.ini"],
        ["AppData/local/totalcmd/totalcommander.bar", "totalcmd/totalcommander.bar"],
    ]
    templates = [
        ["AppData/local/totalcmd/wincmd_dirs.ini", "totalcmd/wincmd_dirs_template.ini"]
    ]

[tasks.windows-terminal]
    # Looks like a random path but it's official: https://learn.microsoft.com/en-us/windows/terminal/install#settings-json-file
    links = [
        ["AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json", "rc-files/windows-terminal"],
    ]

[tasks.eclipse]
    links = [
        [".eclipse", "eclipse"],
        [".vrapperrc", "rc-files/vrapperrc"]
    ]

[macros.powershell-check-modules]
    prefix = ["cmd", "/c", "powershell", "-NoProfile", "-Command", "Import-Module"]

[macros.powershell-install-module]
    prefix = ["cmd", "/c", "powershell", "-NoProfile", "-Command", "Install-Module"]

[tasks.powershell-modules]
    rejects = [
        ["@powershell-check-modules", "PSCX,ZLocation,PSReadline,posh-git,Recycle"]
    ]
    # Install nuget provider for PowerShellGet and install favourite modules
    cmds = [
        ["cmd", "/c", "powershell", "-NoProfile", "-Command", "Install-PackageProvider", "-Name", "NuGet", "-MinimumVersion", "2.8.5.201"],
        ["cmd", "/c", "powershell", "-NoProfile", "-Command", "Set-PSRepository", "PSGallery", "-InstallationPolicy", "Trusted"],
        ["@powershell-install-module", "PSCX", "-AllowClobber"],
        ["@powershell-install-module", "ZLocation"],
        ["@powershell-install-module", "PSReadline", "-Force"],
        ["@powershell-install-module", "Recycle"],
        ["@powershell-install-module", "posh-git"],
    ]

[tasks.powershell]
    deps = ["powershell-modules"]
    # Set execution policy in 64 and 32 bit modes
    cmds = [
        ["cmd", "/c", "powershell",                                          "-NoProfile", "-Command", "Set-ExecutionPolicy", "-Scope", "CurrentUser", "RemoteSigned"],
        ["cmd", "/c", "%windir%/syswow64/WindowsPowerShell/v1.0/powershell", "-NoProfile", "-Command", "Set-ExecutionPolicy", "-Scope", "CurrentUser", "RemoteSigned"],
        ["cmd", "/c", "powershell", "-NoProfile", "-Command", "Update-Help"],
    ]
    links = [
        ["Documents/WindowsPowerShell", "WindowsPowerShell"],
    ]

[tasks.visualstudio]
    # Make it so that double clicking on a TFS Pending Change item opens the diff viewer rather than the file
    cmds = [
        ["reg", "add", 'HKCU\Software\Microsoft\VisualStudio\14.0\TeamFoundation\SourceControl\Behavior', "/v", "DoubleClickOnChange", "/t", "REG_DWORD", "/d", "00000001", "/f"],
        ["reg", "add", 'HKCU\Software\Microsoft\VisualStudio\15.0\TeamFoundation\SourceControl\Behavior', "/v", "DoubleClickOnChange", "/t", "REG_DWORD", "/d", "00000001", "/f"]
    ]
    links = [
        [".vsvimrc", "rc-files/vsvimrc"],
    ]

[tasks.windows-tweaks]
    # (Try to) Disable those annoying freemium sideloading apps you get after each major update
    cmds = [
        ["reg", "add", 'HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager', "/v", "SilentInstalledAppsEnabled", "/t", "REG_DWORD", "/d", "00000000", "/f"],
    ]

[macros.powershell-create-link-start-home]
    # Next parameter after macro is location of link file
    # Target path still needs to be specified to tell where to link to
    prefix = ["cmd", "/c", "powershell", "-NoProfile", "-Command", "${HM_SRC}/WindowsPowershell/Scripts/New-ShellLink.ps1",
                "-Force", "-LinkOutputPath"]
    suffix = ["-StartPath", "'%USERPROFILE%'"]

[macros.powershell-create-link]
    # Next parameter after macro is location of link file
    # Target path still needs to be specified to tell where to link to
    prefix = ["cmd", "/c", "powershell", "-NoProfile", "-Command", "${HM_SRC}/WindowsPowershell/Scripts/New-ShellLink.ps1",
                "-Force", "-LinkOutputPath"]

[tasks.windows-software]
    # TODO: see what https://gist.github.com/alimbada/449ddf65b4ef9752eff3 has to offer
    # Install software, pin some of them so software's auto-update mechanism doesn't conflict with chocolatey
    cmds = [
        ["choco", "install", "-y", "${HM_SRC}/win-choco-packages.config"],

        ["choco", "pin", "add", "--name", "palemoon"],
        ["choco", "pin", "add", "--name", "firefox"],
        ["choco", "pin", "add", "--name", "notepadplusplus.install"],
        ["choco", "pin", "add", "--name", "adobereader"],

        # Install Windows Terminal app using winget. Choco package tries to do the same thing, only through Get-AppX Powershell cmdlets
        ["powershell", "-NoProfile", "-Command", "${HM_DEST}/AppData/Local/Microsoft/WindowsApps/winget.exe", "install", "Microsoft.WindowsTerminal"]
    ]

# Meta task

[tasks.windows-customization]
    deps = ["windows-customization-git", "windows-customization-shortcuts", "windows-software-customization-irfanview", "windows-software-customization-kitty"]

[tasks.windows-customization-git]
    # Make sure that Git uses GVim as editor, MSYS2 vim doesn't always work properly in terminals. Setting this in the registry so that the git config remains platform indedendent.
    cmds = [
        ["powershell", "-NoProfile", "-Command", "Set-ItemProperty", "-Path", 'HKCU:\Environment', "-Name", "GIT_EDITOR", "-Value", '"gvim.exe -f -i NONE"', "-Force"],

        ["powershell", "-NoProfile", "-Command", "Set-ItemProperty", "-Path", 'HKCU:\Environment', "-Name", "EDITOR", "-Value", "gvim.exe", "-Force"]
    ]

[tasks.windows-customization-shortcuts]
    cmds = [
        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Console.lnk'",
            "-TargetPath", "${HM_DEST}/AppData/Local/Microsoft/WindowsApps/wt.exe"],

        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Command prompt console.lnk'",
            "-TargetPath", "${HM_DEST}/AppData/Local/Microsoft/WindowsApps/wt.exe", "-Arguments", "'new-tab --profile {0caa0dad-35be-5f56-a8ff-afceeeaa6101}'"],

        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Kitty.lnk'",
            "-TargetPath", "C:/ProgramData/chocolatey/lib/kitty/tools/kitty.exe"],

        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/BareTail.lnk'",
            "-TargetPath", "C:/ProgramData/chocolatey/lib/baretail/tools/baretail.exe"],

        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/LogExpert.lnk'",
            "-TargetPath", "c:/ProgramData/chocolatey/lib/logexpert/tools/LogExpert.exe"],

        ["@powershell-create-link",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Calculator.lnk'",
            "-TargetPath", "shell:appsFolder\\Microsoft.WindowsCalculator_8wekyb3d8bbwe!App"],

        ["@powershell-create-link",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Settings.lnk'",
            "-TargetPath", "shell:appsFolder\\windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel"],

        ["@powershell-create-link",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/VLC (Start paused).lnk'",
            "-TargetPath", "'c:/Program Files/VideoLAN/VLC/vlc.exe'", "-Arguments", "'--no-sub-autodetect-file --start-paused'"]
    ]

# Register programs which get installed somewhere in this script and which should start automatically.
[tasks.windows-startup]
    cmds = [
        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/WinManagement.lnk'",
            "-TargetPath", "%DOTFILESPATH%/autohotkey/WinManagement.ahk"],

        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/WinMaximizer.lnk'",
            "-TargetPath", "%DOTFILESPATH%/autohotkey/WinMaximizer.ahk"],

        # Launchy-QT no longer creates a startup link whereas the original Launchy did
        ["@powershell-create-link-start-home",
            "'${HM_DEST}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/Launchy.lnk'",
            "-TargetPath", "C:/ProgramData/chocolatey/lib/launchyqt/tools/Launchy/Launchy.exe"]
    ]

# Irfanview has an annoying 'Delete' shortcut. Disable it
[tasks.windows-software-customization-irfanview]
    accepts = [
        ["cmd", "/c", "powershell", "-NoProfile", "-Command", "if(Select-String", "'Admin_EnableDelete'", "-InputObject", "(Get-Content", "'C:/program files/IrfanView/i_view64.ini'", "-raw", ")){exit", "1}"]
    ]
    cmds = [
        ["cmd", "/c", "powershell", "-NoProfile", "-Command", "Out-File", "-Append", "-Encoding", "ASCII", "-LiteralPath", "'C:/program files/IrfanView/i_view64.ini'", "-InputObject", "'Admin_EnableDelete=0'"]
    ]

# KiTTY has at least one feature which PuTTY doesn't have: it can store its config in the AppData folders
[tasks.windows-software-customization-kitty]
    accepts = [
        ["cmd", "/c", "powershell", "-NoProfile", "-Command", "if(Get-Command", "kitty.exe", "-ErrorAction", "SilentlyContinue){exit", "0}exit", "1"],
        ["cmd", "/c", "powershell", "-NoProfile", "-Command", "exit", "[int](Test-Path", "-PathType", "Leaf", "-LiteralPath", "'c:/ProgramData/chocolatey/lib/kitty/tools/kitty.ini')"]
    ]
    #
#       ["cmd", "/c", "powershell", "-NoProfile", "-Command", "Out-File", "-Encoding", "ASCII", "-LiteralPath", "'c:/ProgramData/chocolatey/lib/kitty/tools/kitty.ini'",
#           "-InputObject", "('[KiTTY]',", "'savemode=dir',", "('configdir='+(Resolve-Path", "'~/AppData/Roaming')+'/KiTTY'))"]
    cmds = [
        ["powershell", "-NoProfile", "-Command", "New-Item", "-Type", "Directory", "'~/AppData/Roaming/KiTTY'", "-Force"],
        ["powershell", "-NoProfile", "-Command", "Set-ItemProperty", "-Path", 'HKCU:\Environment', "-Name", "KITTY_INI_FILE", "-Value", "([string](Resolve-Path '~/AppData/Roaming/KiTTY')+'/kitty.ini')", "-Force"]
    ]
    links = [
        ["AppData/Roaming/KiTTY/kitty.ini", "rc-files/kitty.ini"]
    ]

[tasks.windows-path]
    deps = ["powershell-modules"]
    links = [
        ["bin/lst2mlt.exe", "windows-bin/lst2mlt.exe"],
    ]
    # Make git-cola wrapper which doesn't wait for process to exit
    # (Attempt 1: point to included executable wrapper - this actually will always open a console window)
    # ["powershell", "-NoProfile", "-Command", "C:/ProgramData/chocolatey/tools/shimgen.exe", "--output=\"${HM_DEST}/bin/git-cola.exe\"", "--path=\"${HM_DEST}/AppData/Local/Programs/git-cola/bin/git-cola.exe\"", "--gui"]
    # Attempt 2 using shimgen
    # Then modify path so it includes bin folder plus other stuff.
    # That script depends on PCSX to simplify modifying the PATH variable.
    cmds = [
        ["powershell", "-NoProfile", "-Command", "C:/ProgramData/chocolatey/tools/shimgen.exe", "--gui",
            "--output=\"${HM_DEST}/bin/git-cola.exe\"",
            "--path=\"${HM_DEST}/AppData/Local/Programs/git-cola/Python/pythonw.exe\"",
            "--command=\"${HM_DEST}/AppData/Local/Programs/git-cola/bin/git-cola.exe\""],

        ["powershell", "-NoProfile", "-Command", "${HM_SRC}/win-modify-path.ps1", "'${HM_DEST}'"]
    ]

##################################################################################
# LINUX
##################################################################################

[tasks.zsh]
    links = [
        [".zshrc", "zsh/zshrc"],
        [".zshenv", "zsh/zshenv"],
        [".zsh", "zsh"], # Organize zsh stuff somewhat similar to Vim folder
    ]
    templates = [
        [".localzshrc", "zsh/localzshrc_template"],
        [".localdirs", "zsh/localdirs_template"]
    ]

[tasks.xfce]
    links = [
        [".config/xfce4/terminal/accels.scm", "xdgconfighome/xfce4/terminal/accels.scm"],
    ]

##################################################################################
# SHARED
##################################################################################

[tasks.shared-rc]
    links = [
        [".ackrc", "rc-files/ackrc"],
        [".bash_aliases", "rc-files/bash_aliases"],
        [".bashrc", "rc-files/bashrc"],
        [".config/htop", "xdgconfighome/htop"],
        [".git_global_ignore", "rc-files/git_global_ignore"],
        [".gitconfig", "rc-files/git_global_config"],
        [".kdiff3rc", "rc-files/kdiff3rc"],
        [".lesskey", "rc-files/lesskey"],
        [".pentadactylrc", "rc-files/pentadactylrc"],
        [".themes", "gtk-themes"]
    ]
    templates = [
        [".localgitconfig", "rc-files/git_local_config_template"],
        [".localpentadactylrc", "rc-files/pentadactylrc_local_template"],
    ]

[tasks.vim]
    links = [
        [".vimrc", "vim/main-vimrc"],
        [".vim", "vim"], # Actually a folder
    ]

# TODO: Figure out how we can something similar on Linux
[tasks.vim__windows]
    deps = ["vim__"]
    cmds = [
        ["cmd", "/C", "start", "vim", "-c", "BundleUpdate"]
    ]

##################################################################################
# BINDING ACTIONS
##################################################################################


[tasks.default]
    deps = ["vim", "shared-rc"]

[tasks.default__windows]
    deps = ["eclipse", "powershell", "visualstudio", "totalcmd", "windows-terminal", "windows-tweaks", "windows-software", "windows-customization",
            "windows-path", "default__", "windows-startup"]

[tasks.default__linux]
    deps = ["vim", "shared-rc", "xfce", "zsh"]
